# CI (Cyclic Integrate?)
# .travis.yml
# 
language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx

cache:
  timeout: 360
  cargo: true

script:
  - cargo test --all
  - cargo test --all --no-default-features
  
matrix:
  allow_failures:
    - rust: nightly


# $Gcid$
# 
# To get started with Travis CI
# 1. goto travis-ci.com and sign up with github.
# 2. accept the authorization of Travis CI. You'll be redirected to Github.
# 3. Click the green Activate button, and select the repositories you want 
#    to use with Travis CI.
# 4. Add a `travis.yml` file to your repository to tell Travis CI what to
#    do. The following example specifies a Ruby project that should be
#    built with Ruby 2.2 and the latest versions of JRuby.
# ```yml | .travis.yml
# language: ruby
# rvm:
#  - 2.2
#  - jruby
# ```
# The defaults for Ruby projects are `bundle install` to install
# dependencies, and `rake` to build the project.
# https://docs.travis-ci.com/user/tutorial/